name: myapp

environment:
  sdk: ">=2.12.0 <4.0.0"
dependencies:
  flutter:
      sdk: flutter


dev_dependencies:
  flutter_native_splash: 
  flutter_test:
      sdk: flutter
  flutter_lints: ^3.0.0

flutter_native_splash:
  android_12: true # Enable support for Android 12 and newer.
  color: "#B0C4DE"
  image: assets/splash.png

  
  