name: myapp
publish_to: 'none'

version: 1.0.2+1

environment:
  sdk:  ^3.5.3
dependencies:
  flutter:
      sdk: flutter
  flutter_svg: ^2.1.0
  go_router: ^15.1.1


dev_dependencies:
  flutter_native_splash: ^2.4.3
  flutter_test:
      sdk: flutter
  flutter_lints: ^3.0.0


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  assets:
    - assets/

  
  